### ISSUE TITLE
hausarbeit-jura aktuell nutzbar?/Is hausarbeit-jura actually usable?

### ISSUE THREAD

**Issue by DerBunteBall** [sieversMartin/hausarbeit-jura#1]
Hallo Martin,

ich erlaube mir mal die etwas unformelle Form und schreibe auf Deutsch. 

Hint for the english speaking people: Please ask if this issue is interesteing for you. I will try my best to explain the issue/discussion to you.

Ich versuche aktuell etwas verzweifelt deine Dokumentenklasse hausarbeit-jura ans laufen zu bringen. Entweder gibt es auf Grund neuer Versionen oder anderer Änderungen technische Probleme, oder ich bin schlicht zu blöd dazu.

Wenn ich schlicht hausarbeit-demo.tex zu Grunde lege und versuche das Dokument zu übersetzen, klappt es weder mit pdfLaTeX, LuaLaTeX oder XeLaTeX.

1. pdfLaTeX wirft verschiedenste Fehler in der Dokuemntenklasse selber. Es beanstandet bereits in Zeile 18 (oder in der Nähe dieser) eine angeblich nicht definierte Kommando-Sequenz. Ich werde mal versuchen, mich durch diese Probleme zu hangeln, bin aber nicht der LaTeX König. Ich habe nur das Gefühl, dass mit pdfLaTeX die größte Chance besteht, dass ganze ans laufen zu bekommen. Warum wird aus den folgenden Infos ersehbar.
2. LuaLaTeX ist komplett verloren. Es wirft UTF-8 Fehler in der genutzten jurabook Klasse aus (ich denke jurabook ist nicht in UTF-8 vorhanden - was durch die Ausgabe des file Command bestärkt wird: jurabook.cls: LaTeX auxiliary file, ISO-8859 text (file schätzt meines Wissens nach nur, dass muss nicht immer wahr sein wenn es um Zeichensätze geht.)). Ich vermute schlicht, dass jurabook nicht mit LuaLaTeX und XeLaTeX kompatibel ist. Insbesondere wenn man UTF-8 im Standard nutzt.
3. XeLaTeX erklärt sich selbst mit dem Paket microtype uneinverstanden. Das scheint ein generelles Problem zu sein, dass XeLaTeX nahezu vollständig inkompatibel mit XeLaTeX ist (dazu findet sich alles in der microtype Dokumentation). Konkret wird gemeldet das Text Expansion nicht unterstützt wird. Ich denke das weitere FEhler auftachen würden - schon wegen UTF-8 - denke aber das Packagefehler schon sehr früh zum Übersetzugnsstop führen. Alleien deshalb kommmen die dann wohl nicht hoch.

Probiert habe ich das ganze mit MacTeX (als Editor TeXShop - die Distribution ist wohl TeXLive) und MiKTeX (Wohl heute eine eigene Distribution - keine Ahnung von MiKTeX, habe es nur in meiner Verzweifelung auch in einer Windows 10 VM getestet).

Daher verkürzt meine Frage: Ist aktuell ein Dokument mit hausarbeit-jura erstellbar? Die jura Klasse von Felix Braun geht zwar mit XeLaTeX, jedoch ist das Inhaltsverzeichnis irgendwie kaputt. Das ändert die Buchstaben/Zahlen nicht und die Klasse ist allgemein etwas aus der Zeit gefallen.

Als kleine Nebenfrage: Der Klasse hausarbeit-jura würde eine Möglichkeit die Schriftart zu setzen sehr gut stehen. Soweit ich das asu dem Klassenfile ersehen ikann, ist diese fix gesetzt. Übersehe ich einen Weg diese zu ändern? Dachte dran im fAlle von LuaLaTeX und XeLaTeX schlicht \setmainfont nochmals aufzurufen. Was nun aber nicht geht, da die Klasse nicht mit XeLaTeX und LuaLaTeX geht. Mir persönlich erscheint dies besser zu realisieren zu sein, wenn man Kompatibilität mit XeLaTeX oder LuaLaTeX erreichen würde (wie oben erwähnt steht hier wohl jurabook im Weg). Warum gerade dieser Weg: Kurz um, die Welt da draußen bentutz leider proprietäre Schriftarten wie die von Microsoft und Co.. Das verwenden dieser ist in pdfLaTeX - meines Wissens nach - nicht möglich. Da LuaLaTeX und XeLaTeX sowohl mit UTF-8 arbeiten, als auch True- wie Open-Type Schriften untesützten, hilft das viel. Schriftarten werden gerne von Dozenten, im Rahmen der Formalien, vorgegeben.

Für Frückfragen und anderes kansnt du mich jeder zeit kontaktieren.

Nette Grüße

**Comment by sieversMartin** [comment]
Hallo,

ja, die Klasse ist aktuell nutzbar. Allerdings hat sie wie viele andere Klassen auch ein Problem mit einer der letzten Umstellungen des LaTeX-Kernels. Daher muss man aktuell als Workaround in die erste Zeile der .tex-Datei schreiben: `\UseRawInputEncoding`.

Die Schriftart kann wie in jedem LaTeX-Dokument durch Einbindung eines Pakets geändert werden. 

Ich habe die Klasse vor Jahren auf Basis von `jurabook` geschrieben. Für die damalige Anwendung war es vollkommen ausreichend, mit `pdflatex` zu arbeiten. Es ist ein Freizeitprojekt. Entsprechend geht die Entwicklung nur in Schüben vonstatten. Ich nehme die Kritik aber gerne zum Anlass, die Kompatibilität mit `LuaTeX` bzw. `XeTeX` soweit möglich herzustellen. Auch wird die Schriftgröße des Haupttexts anpassbar sein (unter Berücksichtigung der in Word anderen Definition eines "Punkts").

**Comment by sieversMartin** [comment]
Nachtrag: Die Klasse enthält bereits Anpassungen für `XeTeX` und `LuaTeX`. Ich vermute daher, dass es im Laufe der vergangenen Monaten auch hier zu einer Änderung kam, die das Zusammenspiel zerstört hat.

**Comment by DerBunteBall** [comment]
Hallo Martin,

zunächst einmal vielen dAnk für die schnelle Antwort.

Dieser Hinweis hat mein Problem gelöst. Ein Übersetzen mit pdfLaTeX funktioniert damit ohne Probleme. Die Probleme bzgl. LuaLaTeX und XeLaTeX bleiben leider so bestehen.

Im Übrigen sollte das ganze keine Kritik sein. Die Klasse ist wohl aktuell die beste für genau diese Aufgabe. Es sind ja nur Kleinigkeiten, die "Probleme" machen. Wenn man weiß, was an den Anfang muss, läuft ja alles mit pdfLaTeX.

Ich hoffe das ich die anderen Dinge dann damit erstmal hin bekommen.

Nette Grüße

**Comment by sieversMartin** [comment]
Letztlich ist es sogar nur das `ü` im Argument zu `\ProvidesClass`, das Probleme macht. Das sollte eigentlich nicht sein, da die Datei UTF8-kodiert ist. Ich werde das in der nächste Version entsprechend ändern.

**Comment by DerBunteBall** [comment]
Hallo,

ich kann nicht genau sagen, wo das Problem liegt. Nach dem Log meiner Umgebung stört sich das ganze an jurabook. In TeXLive ist jurabook in ISO-8859-1 hinterlegt. Das geht natürlich entsprechend schief, da LuaLaTeX und XeLaTeX erstmal mit UTF-8 arbeiten.

Was ich aktuell nicht ans laufen bekomme ist die Kopfzeile. Es fehlt leider der Autor name ich erhalte also "-- Matrielnummer" und nicht "Name -- Matrikelnummer".

Nette Grüße

**Comment by DerBunteBall** [comment]
Hallo,

ich habe nun ein paar DInge ans laufen bekommen, andere jedoch noch nicht.

1. Die Kopfzeile wird nicht richtig gesetzt. Ich vermute, dass die Extrahierung des Kurzautor nicht funktioniert. Ich habe das Problem nun hart damit erschlagen, das ich über \lhead den linken Header neu gesetzt habe.
2. Ich bekomme kein Dokument hin, welches sich drucken lässt. Die Kopfzeile wird abgeschnitten und die Seitenzahlen tauchen nicht auf. Ich vermute schwer, dass die Seitengeometrie Probleme macht. Ich habe die Geometrie nur insoweit geändert, dass ich den rechten Seitenrand verändert habe. Da ich mir das abschneiden der Kopf- und Fußzeile nicht anders erklären kann, gehe ich davon aus, dass etwas mit der Seitengeometrie nicht sitmmt (denke das geometry Package geht nicht von A4 aus.). Brauche eigentlich nur ein druckbares Dokument auf A4 mit einem linken Seitenrand von 7cm und rechten Seitenrand von 1,5cm.
3. Irgendwie kommt es zu komischen effekten beim Seitenumbruch. Gelegentlich läuft der Text unter die Seitenzahl und einfach auf die neue Seite.

Wenn es für diese Probleme Lösungen gibt, wäre ich sehr dankbar.

Nette Grüße

**Comment by DerBunteBall** [comment]
Hallo,

das hier ist der Link für ein Minimalbeispiel in ShareLaTeX: https://de.sharelatex.com/read/svshcmtnrhfs

Bekomme die vorgezeichneten Probleme nicht in den Griff. Im ShareLaTeX Output funktioniert es seltsamer Weise. Weder mit TeXShop noch mit MiKTeX kriege ich es ganz ans laufen. Zumindest die Seitenzahlen werden nicht gedruckt.

Nette grüße

**Comment by sieversMartin** [comment]
* Das genutzte LaTeX-System ist älter, so dass es `\UseRawInputEncoding` nicht kennt, d.h. aber auch, dass man es dort nicht braucht.
* `onehalfspace` gibt es nicht, es muss `onehalfspacing` heißen.

Damit läuft alles soweit durch. Auch ein Ausdruck der PDF ist bei mir einwandfrei möglich (inkl. Seitenzahlen). Bitte mal die Druckereinstellungen prüfen.

**Comment by DerBunteBall** [comment]
Bei dem \onehalfspacing hab ich es falsch abgetippt. Habe es richtg in TeXShop und MiKTeX. Das \UseRawInputEncoding hatte ich einfach übernommen, weil ich nicht auf die Version geschaut hatte.

Welche Variante hast du gedruckt? Das komische ist ja gerade, dass die ShareLaTeX Varainte funktioniert. Jedoch fehlen die Seitenzahlen bei Ausdrucken der Varianten von TeXShop und MiKTeX.

Die Druckereinstellungen sind soweit alle korrekt. Insbesondere geht das Gerät richtig von A4 aus.

**Comment by sieversMartin** [comment]
Ich habe das Dokument mit MiKTeX lokal übersetzt und dann das PDF ausgedruckt. Alles wunderbar.

Nachtrag: Da natürlich mit `UseRawInputEncoding`
