### ISSUE TITLE
Option bibformat nicht veränderbar

### ISSUE THREAD

**Issue by Norminator-dot** [sieversMartin/hausarbeit-jura#2]
Hallo,

ich versuche derzeit die Klasse für mich nutzbar zu machen. Vor allem was Zitation und Literaturverzeichnis angeht, muss ich ein paar Dinge anpassen. Ich würde beispielsweise gern das kompakte Format von Jurabib nutzen und nicht das tabelarische. Leider funktioniert die Option \jurabibsetup{bibformat=compress} nicht; ebensowenig wie die anderen Alternativformate, die in der jurabib-Dokumentation beschrieben werden. Ich habe die Option ohne jura-hausarbeit.cls getestet und dort funktioniert sie. 

Andere Optionen bspw. howcited lassen sich ohne Probleme anpassen. 

Ich benutze derzeit den Online-Editor overleaf.
 
Ich wäre für jede Hilfe dankbar. 
LG

**Comment by Norminator-dot** [comment]
Nachtrag: Ich kann die Option verwenden, wenn ich die Klasse direkt bearbeite und lokal im Projektordner sichere.

**Comment by sieversMartin** [comment]
Danke für die Rückmeldung. Das Paket `jurabib` verhindert intern das mehrfache Aufrufen von `\jurabibsetup`. Damit sind aktuell zunächst einmal nur die zwei vordefinierten Varianten möglich, die in der Klasse gesetzt werden.

Man kann allerdings die internen Schalter in der Präambel wunschgemäß setzen:
``` latex
\makeatletter
\jb@tabularfalse % macht bibformat=tabular rückgängig
\jb@compressed@bibtrue % schaltet bibformat=compress ein
\makeatother
```

Mittelfristig wäre es wohl eine gute Idee, das Laden vordefinierter Stile per Klassenoption abschalten zu können, so dass man alles selbst in der Hand hat.

**Comment by Norminator-dot** [comment]
Ebenfalls vielen Dank für die schnelle Antwort! :) 

Das funktioniert nun. Leider sind jetzt noch ein paar andere Probleme mit jurabib aufgetreten, die sich wohl ohne größere Anpassung nicht lösen lassen. (Bspw. müssen einige Kommentare nach Sachtiteln zitiert werden, anstatt nach Autoren.) Ich versuche also gerade biblatex mit dem Stil jura2 einzubinden (biblatex-jura2). Nach langer Recherche glaube ich, es lohnt sich mehr mit einer verbreiteten Plattform wie biblatex + biber zu arbeiten, als mit jurabib das seit über 10 Jahren nicht mehr weiterentwickelt wird und das auch weniger Leute nutzen, also auch weniger (aktuelle) Dokumentation vorhanden ist. 

Dennoch, vielen Dank für die Hilfe!

**Comment by sieversMartin** [comment]
Ich kann Sie nur bestärken, es mit `biblatex` zu versuchen. Ich selbst nutze es seit Jahren ausschließlich. `hausarbeit-jura` hat aber einen anderen Entstehungshintergrund. Damals war `jurabib` die mehr oder wenige einzige (etablierte) Möglichkeit, so dass ich wohl oder übel darauf zurückgegriffen habe.

Es gibt aber auch schon eine Entwicklungsversion, die `biblatex-jura2` nutzt.
